-- AlterTable: Add data field to Session table (generated by PrismaSessionStorage)
-- The data field stores serialized session data (nullable, generated by library)

-- Add column as nullable (if it doesn't exist)
ALTER TABLE "Session" ADD COLUMN IF NOT EXISTS "data" TEXT;

